name: CI Pipeline

on:
  # This will trigger the workflow on pull requests and when pushing to main
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x] # You can adjust the Node.js version

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint to check for linting issues
      - name: Run ESLint
        run: npm run lint

      # Run Prettier to check for formatting issues
      - name: Check code formatting with Prettier
        run: npm run prettier -- --check .

      # Run tests with Jest
      - name: Run tests with Jest
        run: npm run test -- --ci --coverage

      # Build the project
      - name: Build project
        run: npm run build
